[build]
  command = "npm run dev"
  publish = "dist"

[[headers]]
  for = "/*.js"
  [headers.values]
    Content-Type = "application/javascript"

[[headers]]
  for = "/*.mjs"
  [headers.values]
    Content-Type = "application/javascript"

[[headers]]
  for = "/assets/*"
  [headers.values]
    Content-Type = "application/javascript"

# Redirección obligatoria para aplicaciones de una sola página (SPA)
[[redirects]]
  from = "/*"
  to = "/index.html"
  status = 200
